use the header and footer as a single file
hascal/hascal.github.io pull request #1
Opened 2022-10-13 12:38 UTC by shayanfpg9

Hi; 👋
when I was opened the webpage for the first time I saw one of the big problems of website is slow loading and when I read the code I undrestand one of the resoans of this problem is copy header and footer codes into the all of the page 😖,
so I think i can fix it and help you to have a better website 🌹

2022-10-13 16:28 UTC, mmdbalkhi requested changes
We are very pleased and glad about your first contribution to Hascal. This is my first round of reviews.
I am not familiar with HTML and I don't know exactly what the problem is. In the Persian language, Persian `utf-8`characters are not displayed correctly.

Please Fix this issue.

![sc](https://user-images.githubusercontent.com/65954744/195653129-1d4067b5-cf56-4454-b375-1946f008f9d4.png)

2022-10-13 16:28 UTC, mmdbalkhi commented on fa/components/header.html
> +                    <a class="nav-link" data-href="foundation.html">>بنیاد هاسکال</a>
```suggestion
                    <a class="nav-link" data-href="foundation.html">بنیاد هاسکال</a>
```

2022-10-13 16:28 UTC, mmdbalkhi commented on fa/components/header.html
> +                    <a class="nav-link" data-href="style.html">>سبک هاسکال</a>
```suggestion
                    <a class="nav-link" data-href="style.html">سبک هاسکال</a>
```

2022-10-13 16:28 UTC, mmdbalkhi commented on fa/components/header.html
> +                    <a class="nav-link" data-href="https://github.com/hascal/hascal">>سورس کد</a>
```suggestion
                    <a class="nav-link" data-href="https://github.com/hascal/hascal">سورس کد</a>
```

2022-10-13 16:28 UTC, mmdbalkhi commented on fa/index.html
>  <html>
```suggestion
<html lang="fa">
```

2022-10-13 16:28 UTC, mmdbalkhi commented on fa/news.html
> +<html>
```suggestion
<html lang="fa">
```

2022-10-14 15:15 UTC, bistcuite commented
@shayanfpg9
Thanks! Do requested changes by @mmdbalkhi to merge this PR to the repository.

2022-10-16 12:52 UTC, shayanfpg9 commented
I'm so sorry for the trouble but when I tested it on my system everything worked fine but I added your suggestions and now I think it should work for you too 🌹

2022-10-16 13:45 UTC, merged

2022-10-16 13:54 UTC, mmdbalkhi commented
Thank you so much @shayanfpg9 for working on this.